# Generated by Django 5.2.1 on 2026-04-05 18:02

from django.db import migrations, models


def backfill_published_at(apps, schema_editor):
    """Existing rows are all published; set published_at = created so
    feeds that sort by -published_at still order historical data correctly.
    """
    Article = apps.get_model("articles", "Article")
    Article.objects.filter(is_published=True, published_at__isnull=True).update(published_at=models.F("created"))


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_published_at, reverse_code=migrations.RunPython.noop),
    ]
